# Generated by Django 4.0.3 on 2022-07-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('can_edit', 'Edit author'),)},
        ),
    ]
